---

- name: "daily database backup"
  cron:
    user: "{{ main_user }}"
    name: "daily database backup"
    hour: '2'
    minute: '0'
    job: "{{ venv.path }}/bin/python {{ backend_path }}/manage.py backup_db backup"
