---
- name: Find postgresql auth config file to configure authentication
  find: paths="/etc/postgresql/" recurse=yes patterns="pg_hba.conf"
  register: hba_files
  when: database_provider == "postgresql"

- name: Configure postgres authentication for using passwords
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: '^(local\s+all\s+all\s+)peer$'
    line: '\1md5'
    backrefs: true
  with_items: "{{ hba_files.files }}"
  when: database_provider == "postgresql"

- name: Install psycopg2 on system
  pip:
    name: psycopg2
  when: database_provider == "postgresql"

- name: Create database user {{ project_slug }}
  community.postgresql.postgresql_user:
    name: "{{ project_slug }}"
    password: "{{ database_password }}"
  become: true
  become_user: postgres
  when: database_provider == "postgresql"

- name: Create database {{ project_slug }}
  community.postgresql.postgresql_db:
    name: "{{ project_slug }}"
    owner: "{{ project_slug }}"
  become: true
  become_user: postgres
  when: database_provider == "postgresql"
