---
- name: Generate backend /etc/ssh/ RSA host key
  command: "ssh-keygen -q -t ed25519 -a 100 -f {{ backend_identity_file_path }} -C \"\" -N \"\""
  become_user: "{{ main_user }}"
  args:
    creates: "{{ backend_identity_file_path }}"
  register: backend_new_ssh_key

- name: WARNING ABOUT new ssh key
  debug:
    msg: |
      IMPORTANT REMINDER

      A new ssh key has been generated at {{ backend_identity_file_path }}
      - it should be added to the project deploy keys in Gitlab/Github
      so that we can clone it.
  when: backend_new_ssh_key.changed

- name: Get new ssh key contents
  command: "cat {{ backend_identity_file_path }}.pub"
  register: backend_command_output
  when: backend_new_ssh_key.changed

- name: Print ssh key to console
  debug:
    msg: "{{ backend_command_output.stdout }}"
  when: backend_new_ssh_key.changed

- name: get latest backend code
  git:
    repo: '{{ backend_repo }}'
    dest: "{{ backend_path + '/..' if is_mono_repo else backend_path }}"
    key_file: "{{ backend_identity_file_path }}"
    force: true
    version: "{{ backend_branch }}"
    accept_hostkey: true
  become_user: "{{ main_user }}"
  register: clonecode

- name: Install python dependencies
  command:
    cmd: "{{ venv.path }}/bin/pip install -r requirements.txt"
    chdir: "{{ backend_path }}"
  when: clonecode.changed or force_update is defined

- name: Run migrations
  command:
    cmd: "{{ project_slug }}-ctl migrate"
  become: true
  become_user: "{{ main_user }}"
  when: clonecode.changed or force_update is defined

- name: Collect backend static files
  command:
    cmd: "{{ project_slug }}-ctl collectstatic --no-input"
  when: clonecode.changed or force_update is defined

- name: Restart {{ project_slug }} supervisor
  supervisorctl:
    name: "{{ project_slug }}-backend"
    state: restarted
  when: clonecode.changed or force_update is defined
