---
# Package installation tasks
- include_tasks: packages.yml

# Database setup tasks
- include_tasks: database.yml

# User and directory creation tasks
- include_tasks: user_and_directories.yml

# Application setup tasks
- include_tasks: application.yml

# Deployment tasks
- include_tasks: deployment.yml

# Maintenance tasks
- include_tasks: cron.yml
