# Setup maintenance mode
# Deploys a maintenance page and configures nginx to serve it
#
# Required vars:
#  - static_path (usually frontend_static_path)
#  - main_user
#  - project_slug
#  - nginx_conf_filename
#
# Optional vars:
#  - maintenance_logo_source: path to logo file on frontend_static
#  - contact_email: email to display on maintenance page
---
- name: Deploy maintenance page
  template:
    src: "{{ maintenance_page }}.j2"
    dest: "{{ static_path }}/{{ maintenance_page | default('maintenance.html') }}"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0644

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/{{ nginx_conf_filename }}
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload nginx
