---
- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/{{ project_slug }}
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Get node_version
  shell: "cat {{ frontend_path }}/.nvmrc"
  register: node_version

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install node version {{ node_version.stdout }}
  shell: "source /root/.nvm/nvm.sh && nvm install {{ node_version.stdout }}"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.nvm/{{ node_version.stdout }}_installed"

- name: add environment variable file
  template:
    src: frontend.env
    dest: "{{ frontend_path }}/.env"
