---
- name: Frontend ssh key config
  block:
    - name: Generate frontend /etc/ssh/ RSA host key
      command: "ssh-keygen -q -t ed25519 -a 100 -f {{ frontend_identity_file_path }}
                -C \"\" -N \"\""
      become_user: "{{ main_user }}"
      args:
        creates: "{{ frontend_identity_file_path }}"
      register: frontend_new_ssh_key

    - name: WARNING ABOUT new ssh key
      debug:
        msg: |
          IMPORTANT REMINDER

          A new ssh key has been generated at {{ frontend_identity_file_path }}
          - it should be added to the project deploy keys in Gitlab/Github
          so that we can clone it.
      when: frontend_new_ssh_key.changed

    - name: Get new ssh key contents
      command: "cat {{ frontend_identity_file_path }}.pub"
      register: command_output
      when: frontend_new_ssh_key.changed

    - name: Print ssh key to console
      debug:
        msg: "{{command_output.stdout}}"
      when: frontend_new_ssh_key.changed
  when: not is_mono_repo

- name: get latest frontend code
  git:
    repo: '{{ frontend_repo }}'
    dest: "{{ backend_path + '/..' if is_mono_repo else backend_path }}"
    key_file: "{{ frontend_identity_file_path }}"
    accept_hostkey: true
    force: true
    version: "{{ frontend_branch }}"
  become_user: "{{ main_user }}"
  register: clonecode

- name: Install project node dependencies with npm
  # yamllint disable-line rule:line-length
  shell: "source /root/.nvm/nvm.sh && nvm exec {{ node_version.stdout }} npm install"
  args:
    chdir: "{{ frontend_path }}"
    executable: /bin/bash
  when: clonecode.changed or force_update is defined

- name: Make sure project files have the right owner after installs
  file:
    path: "{{ frontend_path }}"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    recurse: true
    state: directory
  when: clonecode.changed or force_update is defined
