---
- name: SSR config
  block:
    - name: Build frontend code for SSR
      # yamllint disable-line rule:line-length
      shell: "source /root/.nvm/nvm.sh && nvm exec {{ node_version.stdout }} npm build"
      args:
        chdir: "{{ frontend_path }}"
        executable: /bin/bash
      register: build_code
      when: clonecode.changed or force_update is defined

    - debug: msg="{{ build_code.stdout }}"
      when: clonecode.changed or force_update is defined

    - name: Copy supervisord config to {{ supervisor_conf }}/{{ project_slug }}_frontend.conf
      template:
        src: frontend-supervisor.conf.j2
        dest: "{{ supervisor_conf }}/{{ project_slug }}_frontend.conf"
        owner: root
        group: root
        mode: 0644

    - name: Install {{ project_slug }}-frontend supervisor
      supervisorctl:
        name: "{{ project_slug }}-frontend"
        state: present

    - name: Restart {{ project_slug }}-frontend supervisor
      supervisorctl:
        name: "{{ project_slug }}-frontend"
        state: restarted
      when: clonecode.changed or force_update is defined

  when: frontend_mode == 'SSR'
