---

venv:
  path: /usr/local/telescooop/{{ project_slug }}/backend/venv

backend_path: /telescoop/{{ project_slug}}/backend
supervisor_conf: /etc/supervisor/conf.d

backend_timeout: 30
backend_workers: 1

database_backup:
  hour: 2
  minute: 0
