---

venv:
  path: /usr/local/{{ organization_slug }}/{{ project_slug_for_environment }}/backend/venv

backend_path: /{{ organization_slug }}/{{ project_slug_for_environment }}/backend
backend_settings_path: /etc/{{ organization_slug }}/{{ project_slug_for_environment }}/settings.ini

backend_timeout: 30
backend_workers: 1

database_backup:
  hour: 2
  minute: 0

database_password: "{{ vault_database_password }}"
