---

frontend_static_path: "{{ project_dir }}/frontend_static"
frontend_path: "{{ project_dir }}/frontend{{ '/front' if is_mono_repo else '' }}"
server_uris_passed_to_backend:
  - admin
  - api
  - backup
  - hijack
